from input_deck import inputs


C=[inputs(nb_loops=20000,
         nb_steps=5,
         mutation_type='dynamic',
         nb_mutations=10,
         nb_snapshots=25,
         Nb_sequences=10000),
inputs(nb_loops=100000,
         nb_steps=5,
         mutation_type='static',
         nb_mutations=1,
         nb_snapshots=25,
         Nb_sequences=1000),
inputs(nb_loops=100000,
         nb_steps=5,
         mutation_type='static',
         nb_mutations=10,
         nb_snapshots=25,
         Nb_sequences=1000),

inputs(nb_loops=100000,
         nb_steps=5,
         mutation_type='dynamic',
         nb_mutations=10,
         nb_snapshots=25,
         Nb_sequences=1000),
inputs(nb_loops=20000,
         nb_steps=5,
         mutation_type='static',
         nb_mutations=1,
         nb_snapshots=25,
         Nb_sequences=10000),
   inputs(nb_loops=20000,
         nb_steps=5,
         mutation_type='static',
         nb_mutations=10,
         nb_snapshots=25,
         Nb_sequences=10000),

   ]