#!/bin/bash -l
#PBS -l walltime=4:00:00,nodes=1:ppn=10,mem=15gb
#PBS -m abe
#PBS -M golin010@umn.edu


module load usearch/11.0_64bit
cd ./round3_gp2/nova2/Trial_1

for ((i=1;i<=40;i++));
do
	usearch -fastq_mergepairs "RPI"$i"_S"*"_R1"*".fastq" -fastqout "RPI"$i"_merge.fastq" -relabel @
done
for ((i=1;i<=24;i++));
do
	usearch -search_pcr2 "RPI"$i"_merge.fastq" -fwdprimer TGGTGGTTCTGCTAGC -revprimer TAAGCTTTTGTTCGGATCC -strand plus -fastqout "RPI"$i"_align.fastq"
done
for ((i=25;i<=32;i++));
do
	usearch -search_pcr2 "RPI"$i"_merge.fastq" -fwdprimer AAGGAGATATACATATGGCTAGC -revprimer CCTCCACCGGATCC -strand plus -fastqout "RPI"$i"_align.fastq"
done

for ((i=33;i<=40;i++));
do
	usearch -search_pcr2 "RPI"$i"_merge.fastq" -fwdprimer CGGAGGCAGTGCTAGC -revprimer GCCTCCTCCGGATCC -strand plus -fastqout "RPI"$i"_align.fastq"
done

for ((i=1;i<=40;i++));
do
	usearch -fastq_filter "RPI"$i"_align.fastq" -fastaout "RPI"$i"_filter.fasta" -fastq_maxee 1 -fastq_maxns 0 
	usearch -fastx_uniques "RPI"$i"_align.fastq" -fastaout "RPI"$i"_Unique.fasta" -sizeout -relabel "RPI"$i. 
done

